"""add continent field

Revision ID: c25af52a672b
Revises: 44c2a2cfe613
Create Date: 2026-05-21 10:13:24.443607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25af52a672b'
down_revision: Union[str, Sequence[str], None] = '44c2a2cfe613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'countries', 
        sa.Column('continent', sa.String(), nullable=True)
    )

    op.execute("UPDATE countries SET continent = 'Unknown' WHERE continent IS NULL")

    op.alter_column(
        "countries",
        "continent",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'continent')
    # ### end Alembic commands ###
